---
datasources:
  default:
    url: jdbc:mysql://${MYSQL_HOST:localhost}/${MYSQL_DATABASE:book}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER:book}
    password: ${MYSQL_PASSWORD:book}
    validationQuery: Select 1
    testOnBorrow: true

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true